export const locations = [
  {
    id: "simpsons-home",
    name: "The Simpsons' Home",
    slug: "simpsons-home",
    shortDescription: "The famous family house at 742 Evergreen Terrace.",
    fullDescription:
      "The Simpsons' home is the heart of the series and the place where most of Springfield's chaos begins. From the living room couch to the kitchen, backyard, and garage, the house has hosted family arguments, quiet moments, prank calls, and plenty of classic scenes that define the show. It feels lived-in, ordinary, and iconic all at once, which is exactly why it works so well as the family's main setting.",
    thumbnail: "./assets/simpsons_home.jpeg",
    coverImage: "./assets/gallery/simpsons-home/cover.png",
    gallery: [
      {
        id: 1,
        title: "Front View",
        image: "./assets/gallery/simpsons-home/gallery-1.jpg",
        alt: "Front view of the Simpsons' house",
        fullscreen: true,
      },
      {
        id: 2,
        title: "House Sign",
        image: "./assets/gallery/simpsons-home/gallery-2.png",
        alt: "The Simpsons house sign",
        fullscreen: true,
      },
      {
        id: 3,
        title: "Springfield Backdrop",
        image: "./assets/gallery/simpsons-home/simpsons_3.png",
        alt: "Springfield landscape behind the house",
        fullscreen: true,
      },
      {
        id: 4,
        title: "Town View",
        image: "./assets/gallery/simpsons-home/gallery_4.png",
        alt: "Springfield town view",
        fullscreen: true,
      },
      {
        id: 5,
        title: "Homer Portrait",
        image: "./assets/gallery/simpsons-home/gallery_5.png",
        alt: "Homer Simpson portrait used for the home cover",
        fullscreen: true,
      },
      {
        id: 6,
        title: "Bart Portrait",
        image: "./assets/gallery/simpsons-home/gallery_6.png",
        alt: "Bart Simpson portrait",
        fullscreen: true,
      },
    ],
  },
  {
    id: "moes-tavern",
    name: "Moe's Tavern",
    slug: "moes-tavern",
    shortDescription: "Springfield's most famous bar, run by Moe Szyslak.",
    fullDescription:
      "Moe's Tavern is Springfield's best-known neighborhood bar, and it has served as the backdrop for countless prank calls, late-night conversations, and moments of absurdity. The place is rough around the edges, dimly lit, and always one bad decision away from disaster, which makes it perfect for the show's darker humor. Even when the episodes move away from the bar itself, Moe's Tavern still feels like one of the most recognizable places in the entire series.",
    thumbnail: "./assets/moes_tavern.webp",
    coverImage: "./assets/gallery/moes-tavern/cover.png",
    gallery: [
      {
        id: 1,
        title: "Moe Portrait",
        image: "./assets/gallery/moes-tavern/gallery-1.jpeg",
        alt: "Moe's Tavern thumbnail",
        fullscreen: true,
      },
      {
        id: 2,
        title: "Little Rascals",
        image: "./assets/gallery/moes-tavern/gallery-1.png",
        alt: "Moe Szyslak as a child in The Little Rascals",
        fullscreen: true,
      },
      {
        id: 3,
        title: "Hank Azaria",
        image: "./assets/gallery/moes-tavern/gallery-2.jpeg",
        alt: "Hank Azaria portrait",
        fullscreen: true,
      },
      {
        id: 4,
        title: "Homer Portrait",
        image: "./assets/gallery/moes-tavern/moe_3.jpeg",
        alt: "Homer Simpson portrait",
        fullscreen: true,
      },
      {
        id: 5,
        title: "Bart Portrait",
        image: "./assets/gallery/moes-tavern/moes_4.jpeg",
        alt: "Bart Simpson portrait",
        fullscreen: true,
      },
      {
        id: 6,
        title: "Tavern Exterior",
        image: "./assets/gallery/moes-tavern/moes_5.jpeg",
        alt: "Moe's Tavern thumbnail exterior",
        fullscreen: true,
      },
    ],
  },
  {
    id: "kwik-e-mart",
    name: "Kwik-E-Mart",
    slug: "kwik-e-mart",
    shortDescription: "Springfield's legendary convenience store run by Apu.",
    fullDescription:
      "The Kwik-E-Mart is Springfield's all-hours convenience store, famous for its sugary snacks, questionable bargains, and endless satire of chain stores. Apu turned it into one of the show's most familiar settings, and the place has become shorthand for quick stop shopping, late-night chaos, and the strange charm of everyday Springfield life. It is simple, colorful, and instantly recognizable.",
    thumbnail: "./assets/kwik.webp",
    coverImage: "./assets/gallery/kwik-e-mart/cover.png",
    gallery: [
      {
        id: 1,
        title: "Store Front",
        image: "./assets/gallery/kwik-e-mart/kwik1.png",
        alt: "Kwik-E-Mart thumbnail",
        fullscreen: true,
      },
      {
        id: 2,
        title: "7-Eleven Promotion",
        image: "./assets/gallery/kwik-e-mart/gallery-2.jpg",
        alt: "Kwik-E-Mart 7-Eleven promotion photo",
        fullscreen: true,
      },
      {
        id: 3,
        title: "Universal Studios",
        image: "./assets/gallery/kwik-e-mart/kwik.png",
        alt: "Kwik-E-Mart at Universal Studios",
        fullscreen: true,
      },
      {
        id: 4,
        title: "Apu Portrait",
        image: "./assets/gallery/kwik-e-mart/kwik3.png",
        alt: "Apu Nahasapeemapetilon portrait used for the cover",
        fullscreen: true,
      },
      {
        id: 5,
        title: "Hank Azaria",
        image: "./assets/gallery/kwik-e-mart/kwik4.png",
        alt: "Hank Azaria portrait",
        fullscreen: true,
      },
      {
        id: 6,
        title: "Springfield Stop",
        image: "./assets/gallery/kwik-e-mart/kwik5.png",
        alt: "Springfield city view near the Kwik-E-Mart",
        fullscreen: true,
      },
    ],
  },
];
